package com.gorcyn.sample.greendao.v1.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gorcyn.sample.greendao.v1.model.User;
import com.gorcyn.sample.greendao.v1.model.Address;

import com.gorcyn.sample.greendao.v1.dao.UserDao;
import com.gorcyn.sample.greendao.v1.dao.AddressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig addressDaoConfig;

    private final UserDao userDao;
    private final AddressDao addressDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        addressDaoConfig = daoConfigMap.get(AddressDao.class).clone();
        addressDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        addressDao = new AddressDao(addressDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Address.class, addressDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        addressDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public AddressDao getAddressDao() {
        return addressDao;
    }

}
